# Generated by Django 2.0.6 on 2018-08-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='caption',
            field=models.TextField(null=True),
        ),
    ]
