# Generated by Django 2.0.6 on 2018-08-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('destination', models.CharField(max_length=100)),
                ('picture_url', models.CharField(max_length=1000)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('date_written', models.DateTimeField()),
            ],
        ),
    ]
