# Generated by Django 2.0.6 on 2018-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('picture_url', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('about_me', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
