# Generated by Django 2.0.6 on 2018-08-21 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_embed',
            new_name='embed_url',
        ),
        migrations.AddField(
            model_name='video',
            name='thumb_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
